name: Publish to NPM

on:
  release:
    types: [ created ]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.18.0'
          registry-url: https://registry.npmjs.org/

      - name: Get tagname
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build package
        run: |
          npm ci \
          && npm run build \
          && npm run make_public

      - name: Publish canary
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: contains(steps.vars.outputs.tag, 'canary')
        run: npm publish --tag canary

      - name: Publish latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: "!contains(steps.vars.outputs.tag, 'canary')"
        run: npm publish
